# .github/workflows/docker-publish.yml
name: Build and Publish Docker Image to GHCR

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0, v2.3.4 etc.
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Needed to check out code and read package.json
  packages: write # Needed to push Docker image to GHCR

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or the Node.js version used by your project

      - name: Extract version from package.json
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mcp-proxy-server:${{ steps.get_version.outputs.version }}
            ghcr.io/${{ github.repository }}/mcp-proxy-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max